  services:

    db:
      image: postgres:15.2
      container_name: best_travel

      restart: always

      environment:
        - POSTGRES_DB=best_travel
        - POSTGRES_USER=${DB_USER}
        - POSTGRES_PASSWORD=${DB_PASSWORD}

      ports:
        - "5432:5432"
      volumes:
              - postgres_data:/var/lib/postgresql/data

  volumes:
    postgres_data:


