# ==========================================
# 1. DEFINICIÓN DE VARIABLES GLOBALES
# ==========================================
@hostname = localhost
@port = 8080
@host = http://{{hostname}}:{{port}}
@email = joirv.valencia@pruebajwt.com
@password = Isabella27jwt

### Peticion Post ###
POST {{host}}/api/v1/auth/login
Content-Type: application/json

{
  "email":"{{email}}",
  "pwd": "{{password}}"
}
> {%
    // Captura el String de "data" y lo guarda en la variable global "authToken"
    client.global.set("authToken", response.body.data);
    client.log("¡Token guardado con éxito!: " + response.body.data);
%}