# se usa para configurar el servidor embebido en Spring Boot en lugar de ponerlo en el controlador url /api/v1/nameControlador
serever.servlet.context-path=/api/v1
spring.application.name=CursoSpringBoot
spring.datasource.url=jdbc:postgresql://localhost:5432/best_travel
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=alejandro
spring.datasource.password=debuggeandoideas
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.maximum-pool-size=5
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
