name: Validacion de Codigo Base

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  compilar-y-probar:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: best_travel
          POSTGRES_USER: alejandro
          POSTGRES_PASSWORD: debuggeandoideas
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Descargar codigo del repositorio
        uses: actions/checkout@v4

      - name: Instalar Java JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Compilar y Ejecutar Pruebas Unitarias
        run: mvn clean package
        env:
          # Inyectamos las propiedades usando el puente local de GitHub (127.0.0.1)
          SPRING_DATASOURCE_URL: jdbc:postgresql://127.0.0.1:5432/best_travel
          SPRING_DATASOURCE_USERNAME: alejandro
          SPRING_DATASOURCE_PASSWORD: debuggeandoideas
          # Aseguramos que Flyway también use la base de datos efímera
          SPRING_FLYWAY_URL: jdbc:postgresql://127.0.0.1:5432/best_travel
          SPRING_FLYWAY_USER: alejandro
          SPRING_FLYWAY_PASSWORD: debuggeandoideas
          # Apagamos docker-compose para que no intente buscar archivos locales
          SPRING_DOCKER_COMPOSE_ENABLED: false